### ISSUE TITLE
Como usar

### ISSUE THREAD

**Issue by ricardorohde** [CViniciusSDias/controle-de-tickets#1]
Olá, como faço para usar?

**Comment by CViniciusSDias** [comment]
Olá, Ricardo.
O projeto foi descontinuado, mas se na versão atual ele te atende:

Basta fazer clone do repositório, renomear o arquivo `app/config/parameters.yml.dist` e substituir as configurações para os valores do seu servidor.

Depois disso, basta enviar o código para seu servidor e instalar as dependências do composer.

**Comment by ricardorohde** [comment]
entendi... 
só não sei fazer isso " instalar as dependências do composer. "

**Comment by NunoPP20** [comment]
também achei muito confuso, sei utilizar php, html e gerenciar banco de dados dentro do possível e estou desenvolvendo um site em que precisaria de um sistema de tickets e achei o seu só que não entendi relativamente nada, ao colocar no servidor o arquivo em php parecia estar sem css... enfim pelas suas prints o sistema é muito bom, se o sistema for simples de instalar creio que não custaria nada uma breve explicação em um bloco de notas. Atc.

**Comment by ricardorohde** [comment]
eu nao consegui :(
